# Generated by Django 5.2.4 on 2025-07-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('UNDER_REVIEW', 'UNDER REVIEW'), ('INTERVIEW_SCHEDULED', 'INTERVIEW SCHEDULED'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], default='SUBMITTED', max_length=100)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.IntegerField()),
                ('department_id', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('FIN', 'FINANCE')], max_length=100)),
                ('resume_upload', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'candidates',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('UNDER_REVIEW', 'UNDER REVIEW'), ('INTERVIEW_SCHEDULED', 'INTERVIEW SCHEDULED'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], default=None, max_length=100)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.candidate'),
        ),
    ]
